### ISSUE TITLE
Getting an error with Xeniumranger while converting results to a xenium bundle: the transcript assignments finds cell-Ids that arent present in viz-polygons. Do you know how can I work around that and make sure its right ?

### ISSUE THREAD

**Issue by asmitaL99** [dcjones/proseg#38]
2024-10-02 10:35:12 [runtime] (run:local)       ID.IMPORT_SEGMENTATION.XENIUM_RANGER_CS.XR_IMPORT_TRANSCRIPT_ASSIGNMENTS.fork0.join
2024-10-02 10:35:28 [runtime] (failed)          ID.IMPORT_SEGMENTATION.XENIUM_RANGER_CS.XR_IMPORT_TRANSCRIPT_ASSIGNMENTS

[error] Pipestance failed. Error log at:
project-id/XENIUM_RANGER_CS/XR_IMPORT_TRANSCRIPT_ASSIGNMENTS/fork0/join-u354efd682e/_errors

Log message:
Traceback (most recent call last):
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 648, in _main
    stage.main()
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 617, in main
    self._run(
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 564, in _run
    cmd()
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/external/martian/adapters/python/martian_shell.py", line 618, in <lambda>
    lambda: self._module.join(args, outs, chunk_defs, chunk_outs)
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/mro/insitu/stages/xr_import_transcripts/__init__.py", line 97, in join
    import_transcript_assignments.join(
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/stages/import_transcript_assignments.py", line 69, in join
    results = import_baysor_transcript_assignments(
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/import_transcripts.py", line 84, in import_baysor_transcript_assignments
    baysor_results = BaysorSegmentationResults.deserialize(
  File "/home/asmilags/proseg/Xen_KPMP_038/xeniumranger-xenium3.0/lib/python/turing/engine/xenium_ranger/import_segmentation/baysor.py", line 389, in deserialize
    raise MissingCellPolygon(cell_id_diffs)
turing.engine.xenium_ranger.import_segmentation.baysor.MissingCellPolygon: Found cell IDs in transcript-assignments that are not present in viz-polygons. All cell IDs from transcript-assignments must be present in viz-polygons. The following IDs are missing from viz-polygons: [  2014   8653   9317  11058  11135  11175  12519  12586  15077  15091
  16187  18530  19737  20041  20480  20581  23401  23738  24371  25229
  26995  27589  29680  29893  29924  31984  33471  35002  39114  40135
  43175  43442  44532  45535  45673  47263  52194  52457  53885  54509
  54610  55001  55512  55601  58065  62005  63196  63790  63835  65668
  65849  66316  68669  69243  70346  72397  72480  73470  74226  74714
  76743  77135  78034  78890  80067  80098  80197  80342  80388  81917
  82369  82549  82603  83755  84603  85177  85245  86150  86219  87024
  87368  87554  89464  92239  93249  93280  94134  94587  94820  95007
  95511  95737  98843 101275 101555 101772 102601 102769 103061 103427
 103439 104129 104145 104454 104706 104807 104969 106869 107207 107527
 108525 108806 109009 109787 110235 110374 110717 111191 111586 111793
 111897 112284 113081 114035 115060 115426 115428 115766 115868 116314
 116319 116811 116886 116907 117049 118265 118646 118847 120235 120389
 120629 121239 121437 121787 121951 122237 122901 123328 123669 123701
 124447 125126 125302 125888 126099 126257 126563 126766 127044 127350
 127838 128136 128687 128787 128916 129403 129626 129674 129862 130002
 130256 130280 130612 130770 130970 131292 131432 132197 132513 132721
 132788 132959 133072 133079 133080 133606 133820 133896 134048 134068
 134171 134519 134584 135223 135241 135292 135487 136036 136402 136709
 136839 136882 136935 137000 137227 137375 137511 138148 138258 138352
 138481 138483 138677 138899 138929 139070 139375 139648 139861 139981
 140095 140267 140394 140403 140493 140685 141054 141120 141342 141393
 141522 141545]

Waiting 6 seconds for UI to do final refresh.
Pipestance failed. Use --noexit option to keep UI running after failure.

2024-10-02 10:35:34 Shutting down.
Saving pipestance info to "/home/asmilags/proseg/Xen_KPMP_038/project-id/project-id.mri.tgz"
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
For assistance, upload this file to 10x Genomics by running:

xeniumranger upload <your_email> "/home/asmilags/proseg/Xen_KPMP_038/project-id/project-id.mri.tgz"

**Comment by dcjones** [comment]
It seems xeniumranger 3 introduced some incompatibilities. I just released proseg 1.1.6 which should fix these issues. Thanks for reporting!
